SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS RESTAURANT.BASIC_PAID_ITEM;
DROP TABLE IF EXISTS RESTAURANT.EMPLOYEE_MONEY_GIFT;
DROP TABLE IF EXISTS RESTAURANT.JOB_INFO;
DROP TABLE IF EXISTS RESTAURANT.WORK_CONTENT_MONEY;
DROP TABLE IF EXISTS RESTAURANT.EMPLOYEE_GIFT_BALANCE;
DROP TABLE IF EXISTS RESTAURANT.PAID_BALANCE;
DROP TABLE IF EXISTS RESTAURANT.EMPLOYEE_PAID;
DROP TABLE IF EXISTS RESTAURANT.EMPLOYEE_ACTION;
DROP TABLE IF EXISTS RESTAURANT.OPERATION;
DROP TABLE IF EXISTS RESTAURANT.BUSINESS;
DROP TABLE IF EXISTS RESTAURANT.EMPLOYEE;
DROP TABLE IF EXISTS RESTAURANT.PAID_ITEM;
DROP TABLE IF EXISTS RESTAURANT.JOB;
DROP TABLE IF EXISTS RESTAURANT.OFFICE;
DROP TABLE IF EXISTS RESTAURANT.OFFICE_PRODUCT;
DROP TABLE IF EXISTS RESTAURANT.PAID_CONTENT_ITEM;
DROP TABLE IF EXISTS RESTAURANT.PAID_PROJECT;
DROP TABLE IF EXISTS RESTAURANT.OFFICE_TYPE;
DROP TABLE IF EXISTS RESTAURANT.RES;
DROP TABLE IF EXISTS RESTAURANT.RES_CLASS;




/* Create Tables */

CREATE TABLE RESTAURANT.BASIC_PAID_ITEM
(
	ID varchar(32) NOT NULL,
	BALANCE varchar(32) NOT NULL,
	CATEGORY varchar(32) NOT NULL,
	MONEY decimal(19,4) NOT NULL,
	CALC_PARAM decimal(19,4) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.BUSINESS
(
	ID varchar(32) NOT NULL,
	TYPE varchar(16) NOT NULL,
	START_TIME datetime NOT NULL,
	STATUS varchar(12) NOT NULL,
	DESCRIPTION varchar(512),
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.EMPLOYEE
(
	ID varchar(32) NOT NULL,
	NAME varchar(100) NOT NULL,
	PHONE varchar(32),
	STATUS varchar(12) NOT NULL,
	OFFICE varchar(32) NOT NULL,
	JOIN_DATE datetime NOT NULL,
	WORK_CODE varchar(32),
	JOB varchar(32) NOT NULL,
	LEVEL varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.EMPLOYEE_ACTION
(
	ID varchar(32) NOT NULL,
	EMPLOYEE_ID varchar(32) NOT NULL,
	VALID_TIME datetime NOT NULL,
	BUSINESS varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.EMPLOYEE_GIFT_BALANCE
(
	ID varchar(32) NOT NULL,
	MONEY decimal(19,4) NOT NULL,
	CATEGORY varchar(32) NOT NULL,
	BALANCE varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.EMPLOYEE_MONEY_GIFT
(
	ID varchar(32) NOT NULL,
	MONEY decimal(19,4) NOT NULL,
	CATEGORY varchar(32) NOT NULL,
	BALANCE varchar(32),
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.EMPLOYEE_PAID
(
	ID varchar(32) NOT NULL,
	TOTAL_MONEY decimal(19,4) NOT NULL,
	PAID_MONEY decimal(19,4) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.JOB
(
	ID varchar(32) NOT NULL,
	OFFICE_TYPE varchar(32) NOT NULL,
	NAME varchar(32) NOT NULL,
	PRI int NOT NULL,
	ENABLE boolean NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.JOB_INFO
(
	ID varchar(32) NOT NULL,
	OFFICE varchar(32) NOT NULL,
	WORK_CODE varchar(32),
	JOB varchar(32) NOT NULL,
	LEVEL varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.OFFICE
(
	ID varchar(32) NOT NULL,
	NAME varchar(100) NOT NULL,
	ADDRESS varchar(200),
	STATUS varchar(12) NOT NULL,
	BOTIME datetime NOT NULL,
	OFFICE_TYPE varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.OFFICE_PRODUCT
(
	RES varchar(32) NOT NULL,
	OFFICE varchar(32) NOT NULL,
	PRIMARY KEY (RES, OFFICE)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.OFFICE_TYPE
(
	ID varchar(32) NOT NULL,
	NAME varchar(32) NOT NULL,
	STORE boolean NOT NULL,
	SALE boolean NOT NULL,
	PRODUCE boolean NOT NULL,
	BOTIME datetime NOT NULL,
	ENABLE boolean NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.OPERATION
(
	ID varchar(32) NOT NULL,
	USER_ID varchar(32) NOT NULL,
	USER_NAME varchar(100) NOT NULL,
	TYPE varchar(12) NOT NULL,
	NAME varchar(100) NOT NULL,
	OPERATION_TIME datetime NOT NULL,
	BUSINESS varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.PAID_BALANCE
(
	ID varchar(32) NOT NULL,
	WORK_CONTENT_MONEY decimal(19,4) NOT NULL,
	WORK_DAY decimal(19,4) NOT NULL,
	FULL_WORK_MONEY decimal(19,4) NOT NULL,
	TOTAL_MONEY decimal(19,4) NOT NULL,
	PAID varchar(32),
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.PAID_CONTENT_ITEM
(
	ID varchar(32) NOT NULL,
	MONEY decimal(19,4) NOT NULL,
	RES varchar(32) NOT NULL,
	PAID_PROJECT varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.PAID_ITEM
(
	ID varchar(32) NOT NULL,
	PAID_PROJECT varchar(32) NOT NULL,
	CATEGORY varchar(32) NOT NULL,
	JOB varchar(32) NOT NULL,
	LEVEL varchar(32) NOT NULL,
	MONEY decimal(19,4) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.PAID_PROJECT
(
	ID varchar(32) NOT NULL,
	NAME varchar(32) NOT NULL,
	BOTIME datetime NOT NULL,
	OFFICE_TYPE varchar(32) NOT NULL,
	FULL_WORK_MONEY decimal(19,4) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.RES
(
	ID varchar(32) NOT NULL,
	NAME varchar(128) NOT NULL,
	RES_CLASS varchar(32) NOT NULL,
	ENABLE boolean NOT NULL,
	BOTIME datetime NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.RES_CLASS
(
	ID varchar(32) NOT NULL,
	NAME varchar(128) NOT NULL,
	PRODUCT boolean NOT NULL,
	SEMI boolean NOT NULL,
	RAW boolean NOT NULL,
	CATEGORY varchar(32) NOT NULL,
	BOTIME datetime NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.WORK_CONTENT_MONEY
(
	ID varchar(32) NOT NULL,
	RES varchar(32) NOT NULL,
	MONEY decimal(19,4) NOT NULL,
	BALANCE varchar(32) NOT NULL,
	COUNT decimal(19,4) NOT NULL,
	PRICE decimal(19,4) NOT NULL,
	WORK_CODE varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;



/* Create Foreign Keys */

ALTER TABLE RESTAURANT.EMPLOYEE_ACTION
	ADD FOREIGN KEY (BUSINESS)
	REFERENCES RESTAURANT.BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.OPERATION
	ADD FOREIGN KEY (BUSINESS)
	REFERENCES RESTAURANT.BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.EMPLOYEE_ACTION
	ADD FOREIGN KEY (EMPLOYEE_ID)
	REFERENCES RESTAURANT.EMPLOYEE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.EMPLOYEE_MONEY_GIFT
	ADD FOREIGN KEY (ID)
	REFERENCES RESTAURANT.EMPLOYEE_ACTION (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.JOB_INFO
	ADD FOREIGN KEY (ID)
	REFERENCES RESTAURANT.EMPLOYEE_ACTION (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.EMPLOYEE_PAID
	ADD FOREIGN KEY (ID)
	REFERENCES RESTAURANT.EMPLOYEE_ACTION (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.PAID_BALANCE
	ADD FOREIGN KEY (ID)
	REFERENCES RESTAURANT.EMPLOYEE_ACTION (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.EMPLOYEE_MONEY_GIFT
	ADD FOREIGN KEY (BALANCE)
	REFERENCES RESTAURANT.EMPLOYEE_GIFT_BALANCE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.PAID_BALANCE
	ADD FOREIGN KEY (PAID)
	REFERENCES RESTAURANT.EMPLOYEE_PAID (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.JOB_INFO
	ADD FOREIGN KEY (JOB)
	REFERENCES RESTAURANT.JOB (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.EMPLOYEE
	ADD FOREIGN KEY (JOB)
	REFERENCES RESTAURANT.JOB (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.PAID_ITEM
	ADD FOREIGN KEY (JOB)
	REFERENCES RESTAURANT.JOB (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.JOB_INFO
	ADD FOREIGN KEY (OFFICE)
	REFERENCES RESTAURANT.OFFICE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.EMPLOYEE
	ADD FOREIGN KEY (OFFICE)
	REFERENCES RESTAURANT.OFFICE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.OFFICE
	ADD FOREIGN KEY (OFFICE_TYPE)
	REFERENCES RESTAURANT.OFFICE_TYPE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.JOB
	ADD FOREIGN KEY (OFFICE_TYPE)
	REFERENCES RESTAURANT.OFFICE_TYPE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.OFFICE_PRODUCT
	ADD FOREIGN KEY (OFFICE)
	REFERENCES RESTAURANT.OFFICE_TYPE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.PAID_PROJECT
	ADD FOREIGN KEY (OFFICE_TYPE)
	REFERENCES RESTAURANT.OFFICE_TYPE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.WORK_CONTENT_MONEY
	ADD FOREIGN KEY (BALANCE)
	REFERENCES RESTAURANT.PAID_BALANCE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.BASIC_PAID_ITEM
	ADD FOREIGN KEY (BALANCE)
	REFERENCES RESTAURANT.PAID_BALANCE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.EMPLOYEE_GIFT_BALANCE
	ADD FOREIGN KEY (BALANCE)
	REFERENCES RESTAURANT.PAID_BALANCE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.PAID_CONTENT_ITEM
	ADD FOREIGN KEY (PAID_PROJECT)
	REFERENCES RESTAURANT.PAID_PROJECT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.PAID_ITEM
	ADD FOREIGN KEY (PAID_PROJECT)
	REFERENCES RESTAURANT.PAID_PROJECT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.OFFICE_PRODUCT
	ADD FOREIGN KEY (RES)
	REFERENCES RESTAURANT.RES (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.WORK_CONTENT_MONEY
	ADD FOREIGN KEY (RES)
	REFERENCES RESTAURANT.RES (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.PAID_CONTENT_ITEM
	ADD FOREIGN KEY (RES)
	REFERENCES RESTAURANT.RES (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.RES
	ADD FOREIGN KEY (RES_CLASS)
	REFERENCES RESTAURANT.RES_CLASS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



