SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS RESTAURANT.OPERATION;
DROP TABLE IF EXISTS RESTAURANT.JOB_INFO;
DROP TABLE IF EXISTS RESTAURANT.REWARD_AND_PUNISHMENT;
DROP TABLE IF EXISTS RESTAURANT.EMPLOYEE_ACTION;
DROP TABLE IF EXISTS RESTAURANT.BUSINESS;
DROP TABLE IF EXISTS RESTAURANT.EMPLOYEE;
DROP TABLE IF EXISTS RESTAURANT.PAID_ITEM;
DROP TABLE IF EXISTS RESTAURANT.JOB_LEVEL;
DROP TABLE IF EXISTS RESTAURANT.JOBS;
DROP TABLE IF EXISTS RESTAURANT.OFFICE;
DROP TABLE IF EXISTS RESTAURANT.PAID_PROJECT;
DROP TABLE IF EXISTS RESTAURANT.OFFICE_TYPE;




/* Create Tables */

CREATE TABLE RESTAURANT.BUSINESS
(
	ID varchar(32) NOT NULL,
	TYPE varchar(12) NOT NULL,
	START_TIME datetime NOT NULL,
	STATUS varchar(12) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.EMPLOYEE
(
	ID varchar(32) NOT NULL,
	NAME varchar(100) NOT NULL,
	PHONE varchar(32),
	STATUS varchar(12) NOT NULL,
	OFFICE varchar(32) NOT NULL,
	JOIN_DATE datetime NOT NULL,
	WORK_CODE varchar(32),
	JOB_LEVEL varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.EMPLOYEE_ACTION
(
	ID varchar(32) NOT NULL,
	EMPLOYEE_ID varchar(32) NOT NULL,
	VALID_TIME datetime NOT NULL,
	BUSINESS varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.JOBS
(
	ID varchar(32) NOT NULL,
	OFFICE_TYPE varchar(32) NOT NULL,
	NAME varchar(32) NOT NULL,
	PRI int NOT NULL,
	DISABLE boolean NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.JOB_INFO
(
	ID varchar(32) NOT NULL,
	OFFICE varchar(32) NOT NULL,
	WORK_CODE varchar(32),
	JOB_LEVEL varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.JOB_LEVEL
(
	ID varchar(32) NOT NULL,
	NAME varchar(32) NOT NULL,
	JOBS varchar(32) NOT NULL,
	LEVEL int NOT NULL,
	DISABLE boolean NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.OFFICE
(
	ID varchar(32) NOT NULL,
	NAME varchar(100) NOT NULL,
	ADDRESS varchar(200),
	STATUS varchar(12) NOT NULL,
	BOTIME datetime NOT NULL,
	OFFICE_TYPE varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.OFFICE_TYPE
(
	ID varchar(32) NOT NULL,
	NAME varchar(32) NOT NULL,
	STORE boolean NOT NULL,
	SALE boolean NOT NULL,
	PRODUCE boolean NOT NULL,
	BOTIME datetime NOT NULL,
	DISABLE boolean NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.OPERATION
(
	ID varchar(32) NOT NULL,
	USER_ID varchar(32) NOT NULL,
	USER_NAME varchar(100) NOT NULL,
	TYPE varchar(12) NOT NULL,
	NAME varchar(100) NOT NULL,
	OPERATION_TIME datetime NOT NULL,
	BUSINESS varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.PAID_ITEM
(
	ID varchar(32) NOT NULL,
	PAID_PROJECT varchar(32) NOT NULL,
	CATEGORY varchar(32) NOT NULL,
	JOB_LEVEL varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.PAID_PROJECT
(
	ID varchar(32) NOT NULL,
	NAME varchar(32) NOT NULL,
	BOTIME datetime NOT NULL,
	OFFICE_TYPE varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE RESTAURANT.REWARD_AND_PUNISHMENT
(
	ID varchar(32) NOT NULL,
	ACTION varchar(32) NOT NULL,
	MONEY decimal(19,4) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;



/* Create Foreign Keys */

ALTER TABLE RESTAURANT.OPERATION
	ADD FOREIGN KEY (BUSINESS)
	REFERENCES RESTAURANT.BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.EMPLOYEE_ACTION
	ADD FOREIGN KEY (BUSINESS)
	REFERENCES RESTAURANT.BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.EMPLOYEE_ACTION
	ADD FOREIGN KEY (EMPLOYEE_ID)
	REFERENCES RESTAURANT.EMPLOYEE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.JOB_INFO
	ADD FOREIGN KEY (ID)
	REFERENCES RESTAURANT.EMPLOYEE_ACTION (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.REWARD_AND_PUNISHMENT
	ADD FOREIGN KEY (ACTION)
	REFERENCES RESTAURANT.EMPLOYEE_ACTION (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.JOB_LEVEL
	ADD FOREIGN KEY (JOBS)
	REFERENCES RESTAURANT.JOBS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.JOB_INFO
	ADD FOREIGN KEY (JOB_LEVEL)
	REFERENCES RESTAURANT.JOB_LEVEL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.EMPLOYEE
	ADD FOREIGN KEY (JOB_LEVEL)
	REFERENCES RESTAURANT.JOB_LEVEL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.PAID_ITEM
	ADD FOREIGN KEY (JOB_LEVEL)
	REFERENCES RESTAURANT.JOB_LEVEL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.EMPLOYEE
	ADD FOREIGN KEY (OFFICE)
	REFERENCES RESTAURANT.OFFICE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.JOB_INFO
	ADD FOREIGN KEY (OFFICE)
	REFERENCES RESTAURANT.OFFICE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.OFFICE
	ADD FOREIGN KEY (OFFICE_TYPE)
	REFERENCES RESTAURANT.OFFICE_TYPE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.PAID_PROJECT
	ADD FOREIGN KEY (OFFICE_TYPE)
	REFERENCES RESTAURANT.OFFICE_TYPE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.JOBS
	ADD FOREIGN KEY (OFFICE_TYPE)
	REFERENCES RESTAURANT.OFFICE_TYPE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESTAURANT.PAID_ITEM
	ADD FOREIGN KEY (PAID_PROJECT)
	REFERENCES RESTAURANT.PAID_PROJECT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



