SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS PLAT_SYSTEM.DICTIONARY;
DROP TABLE IF EXISTS PLAT_SYSTEM.DICTIONARY_CATEGORY;




/* Create Tables */

CREATE TABLE PLAT_SYSTEM.DICTIONARY
(
	ID varchar(32) NOT NULL,
	CATEGORY varchar(32) NOT NULL,
	NAME varchar(100) NOT NULL,
	PRI int NOT NULL,
	ENABLE boolean NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE PLAT_SYSTEM.DICTIONARY_CATEGORY
(
	ID varchar(32) NOT NULL,
	MANAGER_ROLE varchar(32),
	NAME varchar(100) NOT NULL,
	SYSTEM boolean NOT NULL,
	ENABLE boolean NOT NULL,
	BOTIME datetime NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;



/* Create Foreign Keys */

ALTER TABLE PLAT_SYSTEM.DICTIONARY
	ADD FOREIGN KEY (CATEGORY)
	REFERENCES PLAT_SYSTEM.DICTIONARY_CATEGORY (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



